language: python
dist: trusty
python:
    - "2.7"
addons:
  apt:
    packages:
      - gfortran
install:
     - cd symlib/src && make all F90=gfortran
     - cd src && make all F90=gfortran
git:
  depth: 3
