language: python
dist: trusty
python:
    - "2.7"
addons:
  apt:
    packages:
      - gfortran
install:
     - cd symlib/src && make all F90=gfortran && cd ../../
     - cd src && make all F90=gfortran && cd ../
git:
  depth: 3
